# Spring configuration
spring:
  # application properties
  application:
    name: SparkStreaming

  # datasource properties
  datasource:
    url: jdbc:mysql://localhost:3306/traffic_limits?serverTimezone=UTC&createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root

  # JPA and Hibernate properties
  jpa:
    database-platform: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
        ddl-auto: update
    open-in-view: true
    show-sql: true
    generate-ddl: true